import type { ParameterPreset } from '../types/simulation';

export const PRESETS: ParameterPreset[] = [
  {
    id: 'nephrops',
    name: 'Nephrops norvegicus (Norway Lobster)',
    description: 'Complete 4-run study from Gaten et al. (2013) comparing flat vs pointy rhabdoms across light-adapted (FL/PL) and dark-adapted (FA/PA) morphologies.',
    category: 'Decapoda',
    citation: 'Gaten et al. (2013), Adv. Mar. Biol. 107:148',
    parameters: [
      {
        speciesName: 'nephropsfl',
        rhabdomLength: 180,
        rhabdomWidth: 25,
        eyeDiameter: 7800,
        facetWidth: 50,
        apertureDiameter: 3200,
        cytoplasmRefractiveIndex: 1.34,
        rhabdomRefractiveIndex: 1.37,
        blurCircleExtent: 18,
        proximalRhabdomAngle: 0,
      },
      {
        speciesName: 'nephropspl',
        rhabdomLength: 180,
        rhabdomWidth: 25,
        eyeDiameter: 7800,
        facetWidth: 50,
        apertureDiameter: 3200,
        cytoplasmRefractiveIndex: 1.34,
        rhabdomRefractiveIndex: 1.37,
        blurCircleExtent: 18,
        proximalRhabdomAngle: 12.5,
      },
      {
        speciesName: 'nephropsfa',
        rhabdomLength: 180,
        rhabdomWidth: 25,
        eyeDiameter: 6760,
        facetWidth: 50,
        apertureDiameter: 3060,
        cytoplasmRefractiveIndex: 1.34,
        rhabdomRefractiveIndex: 1.37,
        blurCircleExtent: 10,
        proximalRhabdomAngle: 0,
      },
      {
        speciesName: 'nephropspa',
        rhabdomLength: 180,
        rhabdomWidth: 25,
        eyeDiameter: 6760,
        facetWidth: 50,
        apertureDiameter: 3060,
        cytoplasmRefractiveIndex: 1.34,
        rhabdomRefractiveIndex: 1.37,
        blurCircleExtent: 10,
        proximalRhabdomAngle: 12.5,
      },
    ],
  },
  {
    id: 'acanthephyra',
    name: 'Acanthephyra purpurea (Deep-Sea Shrimp)',
    description: 'Deep sea pelagic shrimp optical simulation comparing different blur circle extents (1, 3, 6) across the clear zone.',
    category: 'Caridea',
    citation: 'Moss (2025)',
    parameters: [
      {
        speciesName: 'acanthephyra',
        rhabdomLength: 127,
        rhabdomWidth: 15.8,
        eyeDiameter: 2480,
        facetWidth: 22.5,
        apertureDiameter: 870,
        cytoplasmRefractiveIndex: 1.34,
        rhabdomRefractiveIndex: 1.37,
        blurCircleExtent: 1,
        proximalRhabdomAngle: 0,
      },
      {
        speciesName: 'acanthephyra_bce3',
        rhabdomLength: 127,
        rhabdomWidth: 15.8,
        eyeDiameter: 2480,
        facetWidth: 22.5,
        apertureDiameter: 870,
        cytoplasmRefractiveIndex: 1.34,
        rhabdomRefractiveIndex: 1.37,
        blurCircleExtent: 3,
        proximalRhabdomAngle: 0,
      },
      {
        speciesName: 'acanthephyra_bce6',
        rhabdomLength: 127,
        rhabdomWidth: 15.8,
        eyeDiameter: 2480,
        facetWidth: 22.5,
        apertureDiameter: 870,
        cytoplasmRefractiveIndex: 1.34,
        rhabdomRefractiveIndex: 1.37,
        blurCircleExtent: 6,
        proximalRhabdomAngle: 0,
      },
    ],
  },
  {
    id: 'astacodes',
    name: 'Astacodes (Freshwater Crayfish Model)',
    description: 'Standard benchmark compound eye model for comparative optical resolution and sensitivity analysis.',
    category: 'Astacidea',
    parameters: [
      {
        speciesName: 'astacodes',
        rhabdomLength: 100,
        rhabdomWidth: 10,
        eyeDiameter: 1000,
        facetWidth: 20,
        apertureDiameter: 500,
        cytoplasmRefractiveIndex: 1.34,
        rhabdomRefractiveIndex: 1.37,
        blurCircleExtent: 1,
        proximalRhabdomAngle: 0,
      },
    ],
  },
];
